#
# Samsung CIS camera module

obj-$(CONFIG_VIDEO_SAMSUNG_S5K3AA) += 3xa_sensor.o
obj-$(CONFIG_VIDEO_SAMSUNG_S5K3BA) += 3xa_sensor.o
obj-$(CONFIG_VIDEO_SAMSUNG_S5K4BA) += 4xa_sensor.o
obj-$(CONFIG_VIDEO_SAMSUNG_S5K53BA) += 53bea_sensor.o
obj-$(CONFIG_VIDEO_ADV7180) += adv7180.o
obj-$(CONFIG_VIDEO_SAA7113) += saa7113h.o
obj-$(CONFIG_VIDEO_OV9650) += ov9650.o
